-- =============================================================================
-- 10-adif_schema.sql -- the ADIF reference tier (PostgreSQL, PG-1 database `ionis`)
-- GENERATED by scripts/adif_tier.py from ADIF's published all.json for 3.1.6, 3.1.7. Do not edit by hand: regenerate.
-- Every key carries adif_version: versions coexist and a new release is additive.
-- Enumeration rows are keyed by ADIF's own record key; `record` keeps each exactly as published.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS adif;

-- UPGRADES AN EXISTING DATABASE, NOT ONLY A FRESH ONE (Atlas SPEC R17). This file is
-- re-applied on every start, so each step is idempotent: new tables are created, new
-- columns added, a column that now holds lists widened to text, and the natural-key
-- indexes and cross-reference keys rebuilt from this version set. The cross-reference
-- keys are dropped here, before any column is altered, and re-added at the end.
DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT conrelid::regclass AS t, conname FROM pg_constraint
           WHERE contype = 'f' AND connamespace = 'adif'::regnamespace AND conname LIKE '%\_fk' LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.t, r.conname);
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS adif.release (
    adif_version  text PRIMARY KEY,
    status        text NOT NULL,
    released      timestamptz,
    created       timestamptz,
    source_url    text NOT NULL,
    source_sha256 text NOT NULL,
    loaded_at     timestamptz NOT NULL DEFAULT now()
);

-- The lab-wide CURRENT ADIF version (spec: one pointer; rows pin at write and re-pin only
-- by explicit migration). One row, enforced. Loading a version never moves it: set it
-- deliberately with `adif_tier.py set-current --version X`.
CREATE TABLE IF NOT EXISTS adif.current (
    singleton     boolean PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    adif_version  text NOT NULL REFERENCES adif.release (adif_version),
    set_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS adif.datatype (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    data_type_name                           text,
    data_type_indicator                      text,
    description                              text,
    minimum_value                            text,
    maximum_value                            text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, data_type_name)
);
ALTER TABLE adif.datatype ADD COLUMN IF NOT EXISTS data_type_name text, ADD COLUMN IF NOT EXISTS data_type_indicator text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS minimum_value text, ADD COLUMN IF NOT EXISTS maximum_value text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['data_type_name', 'data_type_indicator', 'description', 'minimum_value', 'maximum_value', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'datatype' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.datatype ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;

CREATE TABLE IF NOT EXISTS adif.field (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    field_name                               text,
    data_type                                text,
    enumeration                              text,
    description                              text,
    header_field                             boolean,
    minimum_value                            text,
    maximum_value                            text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, field_name)
);
ALTER TABLE adif.field ADD COLUMN IF NOT EXISTS field_name text, ADD COLUMN IF NOT EXISTS data_type text, ADD COLUMN IF NOT EXISTS enumeration text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS header_field boolean, ADD COLUMN IF NOT EXISTS minimum_value text, ADD COLUMN IF NOT EXISTS maximum_value text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['field_name', 'data_type', 'enumeration', 'description', 'minimum_value', 'maximum_value', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'field' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.field ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
-- No foreign key on data_type: CREDIT_GRANTED / CREDIT_SUBMITTED name two types
-- ('CreditList,AwardList'). The load checks every listed type instead (see load_sql).

-- ARRL_Section
CREATE TABLE IF NOT EXISTS adif.arrl_section (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    section_name                             text,
    dxcc_entity_code                         text,
    from_date                                timestamptz,
    deleted_date                             timestamptz,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.arrl_section ADD COLUMN IF NOT EXISTS abbreviation text, ADD COLUMN IF NOT EXISTS section_name text, ADD COLUMN IF NOT EXISTS dxcc_entity_code text, ADD COLUMN IF NOT EXISTS from_date timestamptz, ADD COLUMN IF NOT EXISTS deleted_date timestamptz, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['abbreviation', 'section_name', 'dxcc_entity_code', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'arrl_section' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.arrl_section ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.arrl_section_natural;
CREATE UNIQUE INDEX arrl_section_natural ON adif.arrl_section (adif_version, abbreviation);
-- ARRL_Section: dxcc_entity_code holds lists in some rows (e.g. '43,202'); text, no foreign key.

-- Ant_Path
CREATE TABLE IF NOT EXISTS adif.ant_path (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.ant_path ADD COLUMN IF NOT EXISTS abbreviation text, ADD COLUMN IF NOT EXISTS meaning text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['abbreviation', 'meaning', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'ant_path' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.ant_path ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.ant_path_natural;
CREATE UNIQUE INDEX ant_path_natural ON adif.ant_path (adif_version, abbreviation);

-- Award
CREATE TABLE IF NOT EXISTS adif.award (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    award                                    text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.award ADD COLUMN IF NOT EXISTS award text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['award', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'award' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.award ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.award_natural;
CREATE UNIQUE INDEX award_natural ON adif.award (adif_version, award);

-- Award_Sponsor
CREATE TABLE IF NOT EXISTS adif.award_sponsor (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    sponsor                                  text,
    sponsoring_organization                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.award_sponsor ADD COLUMN IF NOT EXISTS sponsor text, ADD COLUMN IF NOT EXISTS sponsoring_organization text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['sponsor', 'sponsoring_organization', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'award_sponsor' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.award_sponsor ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.award_sponsor_natural;
CREATE UNIQUE INDEX award_sponsor_natural ON adif.award_sponsor (adif_version, sponsor);

-- Band
CREATE TABLE IF NOT EXISTS adif.band (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    band                                     text,
    lower_freq_mhz                           numeric,
    upper_freq_mhz                           numeric,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.band ADD COLUMN IF NOT EXISTS band text, ADD COLUMN IF NOT EXISTS lower_freq_mhz numeric, ADD COLUMN IF NOT EXISTS upper_freq_mhz numeric, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['band', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'band' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.band ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.band_natural;
CREATE UNIQUE INDEX band_natural ON adif.band (adif_version, band);

-- Contest_ID
CREATE TABLE IF NOT EXISTS adif.contest_id (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    contest_id                               text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.contest_id ADD COLUMN IF NOT EXISTS contest_id text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['contest_id', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'contest_id' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.contest_id ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.contest_id_natural;
CREATE UNIQUE INDEX contest_id_natural ON adif.contest_id (adif_version, contest_id);

-- Continent
CREATE TABLE IF NOT EXISTS adif.continent (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    continent                                text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.continent ADD COLUMN IF NOT EXISTS abbreviation text, ADD COLUMN IF NOT EXISTS continent text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['abbreviation', 'continent', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'continent' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.continent ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.continent_natural;
CREATE UNIQUE INDEX continent_natural ON adif.continent (adif_version, abbreviation);

-- Credit
CREATE TABLE IF NOT EXISTS adif.credit (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    credit_for                               text,
    sponsor                                  text,
    award                                    text,
    facet                                    text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.credit ADD COLUMN IF NOT EXISTS credit_for text, ADD COLUMN IF NOT EXISTS sponsor text, ADD COLUMN IF NOT EXISTS award text, ADD COLUMN IF NOT EXISTS facet text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['credit_for', 'sponsor', 'award', 'facet', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'credit' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.credit ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.credit_natural;
CREATE UNIQUE INDEX credit_natural ON adif.credit (adif_version, credit_for);

-- DXCC_Entity_Code
CREATE TABLE IF NOT EXISTS adif.dxcc_entity_code (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    entity_code                              integer,
    entity_name                              text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.dxcc_entity_code ADD COLUMN IF NOT EXISTS entity_code integer, ADD COLUMN IF NOT EXISTS entity_name text, ADD COLUMN IF NOT EXISTS deleted boolean, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['entity_name', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'dxcc_entity_code' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.dxcc_entity_code ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.dxcc_entity_code_natural;
CREATE UNIQUE INDEX dxcc_entity_code_natural ON adif.dxcc_entity_code (adif_version, entity_code);

-- EQSL_AG
CREATE TABLE IF NOT EXISTS adif.eqsl_ag (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.eqsl_ag ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['status', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'eqsl_ag' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.eqsl_ag ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.eqsl_ag_natural;
CREATE UNIQUE INDEX eqsl_ag_natural ON adif.eqsl_ag (adif_version, status);

-- Mode
CREATE TABLE IF NOT EXISTS adif.mode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    mode                                     text,
    submodes                                 text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.mode ADD COLUMN IF NOT EXISTS mode text, ADD COLUMN IF NOT EXISTS submodes text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['mode', 'submodes', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'mode' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.mode ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.mode_natural;
CREATE UNIQUE INDEX mode_natural ON adif.mode (adif_version, mode);

-- Morse_Key_Type
CREATE TABLE IF NOT EXISTS adif.morse_key_type (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    characteristics                          text,
    morse_composition                        text,
    examples                                 text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.morse_key_type ADD COLUMN IF NOT EXISTS abbreviation text, ADD COLUMN IF NOT EXISTS meaning text, ADD COLUMN IF NOT EXISTS characteristics text, ADD COLUMN IF NOT EXISTS morse_composition text, ADD COLUMN IF NOT EXISTS examples text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['abbreviation', 'meaning', 'characteristics', 'morse_composition', 'examples', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'morse_key_type' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.morse_key_type ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.morse_key_type_natural;
CREATE UNIQUE INDEX morse_key_type_natural ON adif.morse_key_type (adif_version, abbreviation);

-- Primary_Administrative_Subdivision
CREATE TABLE IF NOT EXISTS adif.primary_administrative_subdivision (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    primary_administrative_subdivision       text,
    dxcc_entity_code                         integer,
    contained_within                         text,
    oblast_no                                text,
    cq_zone                                  text,
    itu_zone                                 text,
    prefix                                   text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.primary_administrative_subdivision ADD COLUMN IF NOT EXISTS code text, ADD COLUMN IF NOT EXISTS primary_administrative_subdivision text, ADD COLUMN IF NOT EXISTS dxcc_entity_code integer, ADD COLUMN IF NOT EXISTS contained_within text, ADD COLUMN IF NOT EXISTS oblast_no text, ADD COLUMN IF NOT EXISTS cq_zone text, ADD COLUMN IF NOT EXISTS itu_zone text, ADD COLUMN IF NOT EXISTS prefix text, ADD COLUMN IF NOT EXISTS deleted boolean, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['code', 'primary_administrative_subdivision', 'contained_within', 'oblast_no', 'cq_zone', 'itu_zone', 'prefix', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'primary_administrative_subdivision' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.primary_administrative_subdivision ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.primary_administrative_subdivision_natural;
-- Primary_Administrative_Subdivision: no column set is unique in every version; reference it by record_key.

-- Propagation_Mode
CREATE TABLE IF NOT EXISTS adif.propagation_mode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    enumeration                              text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.propagation_mode ADD COLUMN IF NOT EXISTS enumeration text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['enumeration', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'propagation_mode' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.propagation_mode ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.propagation_mode_natural;
CREATE UNIQUE INDEX propagation_mode_natural ON adif.propagation_mode (adif_version, enumeration);

-- QSL_Medium
CREATE TABLE IF NOT EXISTS adif.qsl_medium (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    medium                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qsl_medium ADD COLUMN IF NOT EXISTS medium text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['medium', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qsl_medium' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qsl_medium ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qsl_medium_natural;
CREATE UNIQUE INDEX qsl_medium_natural ON adif.qsl_medium (adif_version, medium);

-- QSL_Rcvd
CREATE TABLE IF NOT EXISTS adif.qsl_rcvd (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    meaning                                  text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qsl_rcvd ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS meaning text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['status', 'meaning', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qsl_rcvd' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qsl_rcvd ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qsl_rcvd_natural;
CREATE UNIQUE INDEX qsl_rcvd_natural ON adif.qsl_rcvd (adif_version, status);

-- QSL_Sent
CREATE TABLE IF NOT EXISTS adif.qsl_sent (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    meaning                                  text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qsl_sent ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS meaning text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['status', 'meaning', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qsl_sent' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qsl_sent ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qsl_sent_natural;
CREATE UNIQUE INDEX qsl_sent_natural ON adif.qsl_sent (adif_version, status);

-- QSL_Via
CREATE TABLE IF NOT EXISTS adif.qsl_via (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    via                                      text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qsl_via ADD COLUMN IF NOT EXISTS via text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['via', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qsl_via' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qsl_via ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qsl_via_natural;
CREATE UNIQUE INDEX qsl_via_natural ON adif.qsl_via (adif_version, via);

-- QSO_Complete
CREATE TABLE IF NOT EXISTS adif.qso_complete (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qso_complete ADD COLUMN IF NOT EXISTS abbreviation text, ADD COLUMN IF NOT EXISTS meaning text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['abbreviation', 'meaning', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qso_complete' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qso_complete ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qso_complete_natural;
CREATE UNIQUE INDEX qso_complete_natural ON adif.qso_complete (adif_version, abbreviation);

-- QSO_Download_Status
CREATE TABLE IF NOT EXISTS adif.qso_download_status (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qso_download_status ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['status', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qso_download_status' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qso_download_status ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qso_download_status_natural;
CREATE UNIQUE INDEX qso_download_status_natural ON adif.qso_download_status (adif_version, status);

-- QSO_Upload_Status
CREATE TABLE IF NOT EXISTS adif.qso_upload_status (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.qso_upload_status ADD COLUMN IF NOT EXISTS status text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['status', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'qso_upload_status' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.qso_upload_status ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.qso_upload_status_natural;
CREATE UNIQUE INDEX qso_upload_status_natural ON adif.qso_upload_status (adif_version, status);

-- Region
CREATE TABLE IF NOT EXISTS adif.region (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    region_entity_code                       text,
    dxcc_entity_code                         integer,
    region                                   text,
    prefix                                   text,
    applicability                            text,
    start_date                               timestamptz,
    end_date                                 timestamptz,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.region ADD COLUMN IF NOT EXISTS region_entity_code text, ADD COLUMN IF NOT EXISTS dxcc_entity_code integer, ADD COLUMN IF NOT EXISTS region text, ADD COLUMN IF NOT EXISTS prefix text, ADD COLUMN IF NOT EXISTS applicability text, ADD COLUMN IF NOT EXISTS start_date timestamptz, ADD COLUMN IF NOT EXISTS end_date timestamptz, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['region_entity_code', 'region', 'prefix', 'applicability', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'region' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.region ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.region_natural;
-- Region: no column set is unique in every version; reference it by record_key.

-- Secondary_Administrative_Subdivision
CREATE TABLE IF NOT EXISTS adif.secondary_administrative_subdivision (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    secondary_administrative_subdivision     text,
    dxcc_entity_code                         integer,
    alaska_judicial_district                 text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.secondary_administrative_subdivision ADD COLUMN IF NOT EXISTS code text, ADD COLUMN IF NOT EXISTS secondary_administrative_subdivision text, ADD COLUMN IF NOT EXISTS dxcc_entity_code integer, ADD COLUMN IF NOT EXISTS alaska_judicial_district text, ADD COLUMN IF NOT EXISTS deleted boolean, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['code', 'secondary_administrative_subdivision', 'alaska_judicial_district', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'secondary_administrative_subdivision' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.secondary_administrative_subdivision ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.secondary_administrative_subdivision_natural;
CREATE UNIQUE INDEX secondary_administrative_subdivision_natural ON adif.secondary_administrative_subdivision (adif_version, code);

-- Secondary_Administrative_Subdivision_Alt
CREATE TABLE IF NOT EXISTS adif.secondary_administrative_subdivision_alt (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    dxcc_entity_code                         integer,
    region                                   text,
    district                                 text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.secondary_administrative_subdivision_alt ADD COLUMN IF NOT EXISTS code text, ADD COLUMN IF NOT EXISTS dxcc_entity_code integer, ADD COLUMN IF NOT EXISTS region text, ADD COLUMN IF NOT EXISTS district text, ADD COLUMN IF NOT EXISTS deleted boolean, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['code', 'region', 'district', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'secondary_administrative_subdivision_alt' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.secondary_administrative_subdivision_alt ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.secondary_administrative_subdivision_alt_natural;
CREATE UNIQUE INDEX secondary_administrative_subdivision_alt_natural ON adif.secondary_administrative_subdivision_alt (adif_version, code);

-- Submode
CREATE TABLE IF NOT EXISTS adif.submode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    submode                                  text,
    mode                                     text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
ALTER TABLE adif.submode ADD COLUMN IF NOT EXISTS submode text, ADD COLUMN IF NOT EXISTS mode text, ADD COLUMN IF NOT EXISTS description text, ADD COLUMN IF NOT EXISTS import_only boolean, ADD COLUMN IF NOT EXISTS comments text;
DO $$ DECLARE c text; BEGIN FOREACH c IN ARRAY ARRAY['submode', 'mode', 'description', 'comments'] LOOP
  IF (SELECT data_type FROM information_schema.columns WHERE table_schema = 'adif' AND table_name = 'submode' AND column_name = c) <> 'text' THEN
    EXECUTE format('ALTER TABLE adif.submode ALTER COLUMN %I TYPE text USING %I::text', c, c);
  END IF; END LOOP; END $$;
DROP INDEX IF EXISTS adif.submode_natural;
CREATE UNIQUE INDEX submode_natural ON adif.submode (adif_version, submode);

-- Cross-references ADIF itself defines. A load that violates one fails whole.
ALTER TABLE adif.primary_administrative_subdivision DROP CONSTRAINT IF EXISTS primary_administrative_subdivision_dxcc_entity_code_fk;
ALTER TABLE adif.primary_administrative_subdivision ADD CONSTRAINT primary_administrative_subdivision_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.region DROP CONSTRAINT IF EXISTS region_dxcc_entity_code_fk;
ALTER TABLE adif.region ADD CONSTRAINT region_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.secondary_administrative_subdivision DROP CONSTRAINT IF EXISTS secondary_administrative_subdivision_dxcc_entity_code_fk;
ALTER TABLE adif.secondary_administrative_subdivision ADD CONSTRAINT secondary_administrative_subdivision_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.secondary_administrative_subdivision_alt DROP CONSTRAINT IF EXISTS secondary_administrative_subdivision_alt_dxcc_entity_code_fk;
ALTER TABLE adif.secondary_administrative_subdivision_alt ADD CONSTRAINT secondary_administrative_subdivision_alt_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.submode DROP CONSTRAINT IF EXISTS submode_mode_fk;
ALTER TABLE adif.submode ADD CONSTRAINT submode_mode_fk FOREIGN KEY (adif_version, mode) REFERENCES adif.mode (adif_version, mode);

-- The read-only role sees everything in this schema, now and later.
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ionis_ro') THEN
  GRANT USAGE ON SCHEMA adif TO ionis_ro;
  GRANT SELECT ON ALL TABLES IN SCHEMA adif TO ionis_ro;
  ALTER DEFAULT PRIVILEGES IN SCHEMA adif GRANT SELECT ON TABLES TO ionis_ro;
END IF; END $$;
