-- =============================================================================
-- 10-adif_schema.sql -- the ADIF reference tier (PostgreSQL, PG-1 database `ionis`)
-- GENERATED by scripts/adif_tier.py from ADIF's published all.json for 3.1.6, 3.1.7. Do not edit by hand: regenerate.
-- Every key carries adif_version: versions coexist and a new release is additive.
-- Enumeration rows are keyed by ADIF's own record key; `record` keeps each exactly as published.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS adif;

CREATE TABLE IF NOT EXISTS adif.release (
    adif_version  text PRIMARY KEY,
    status        text NOT NULL,
    released      timestamptz,
    created       timestamptz,
    source_url    text NOT NULL,
    source_sha256 text NOT NULL,
    loaded_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS adif.datatype (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    data_type_name                           text,
    data_type_indicator                      text,
    description                              text,
    minimum_value                            text,
    maximum_value                            text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, data_type_name)
);

CREATE TABLE IF NOT EXISTS adif.field (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    field_name                               text,
    data_type                                text,
    enumeration                              text,
    description                              text,
    header_field                             boolean,
    minimum_value                            text,
    maximum_value                            text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, field_name)
);
-- No foreign key on data_type: CREDIT_GRANTED / CREDIT_SUBMITTED name two types
-- ('CreditList,AwardList'). The load checks every listed type instead (see load_sql).

-- ARRL_Section
CREATE TABLE IF NOT EXISTS adif.arrl_section (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    section_name                             text,
    dxcc_entity_code                         text,
    from_date                                timestamptz,
    deleted_date                             timestamptz,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS arrl_section_natural ON adif.arrl_section (adif_version, abbreviation);
-- ARRL_Section: dxcc_entity_code holds lists in some rows (e.g. '43,202'); text, no foreign key.

-- Ant_Path
CREATE TABLE IF NOT EXISTS adif.ant_path (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS ant_path_natural ON adif.ant_path (adif_version, abbreviation);

-- Award
CREATE TABLE IF NOT EXISTS adif.award (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    award                                    text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS award_natural ON adif.award (adif_version, award);

-- Award_Sponsor
CREATE TABLE IF NOT EXISTS adif.award_sponsor (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    sponsor                                  text,
    sponsoring_organization                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS award_sponsor_natural ON adif.award_sponsor (adif_version, sponsor);

-- Band
CREATE TABLE IF NOT EXISTS adif.band (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    band                                     text,
    lower_freq_mhz                           numeric,
    upper_freq_mhz                           numeric,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS band_natural ON adif.band (adif_version, band);

-- Contest_ID
CREATE TABLE IF NOT EXISTS adif.contest_id (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    contest_id                               text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS contest_id_natural ON adif.contest_id (adif_version, contest_id);

-- Continent
CREATE TABLE IF NOT EXISTS adif.continent (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    continent                                text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS continent_natural ON adif.continent (adif_version, abbreviation);

-- Credit
CREATE TABLE IF NOT EXISTS adif.credit (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    credit_for                               text,
    sponsor                                  text,
    award                                    text,
    facet                                    text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS credit_natural ON adif.credit (adif_version, credit_for);

-- DXCC_Entity_Code
CREATE TABLE IF NOT EXISTS adif.dxcc_entity_code (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    entity_code                              integer,
    entity_name                              text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS dxcc_entity_code_natural ON adif.dxcc_entity_code (adif_version, entity_code);

-- EQSL_AG
CREATE TABLE IF NOT EXISTS adif.eqsl_ag (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS eqsl_ag_natural ON adif.eqsl_ag (adif_version, status);

-- Mode
CREATE TABLE IF NOT EXISTS adif.mode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    mode                                     text,
    submodes                                 text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS mode_natural ON adif.mode (adif_version, mode);

-- Morse_Key_Type
CREATE TABLE IF NOT EXISTS adif.morse_key_type (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    characteristics                          text,
    morse_composition                        text,
    examples                                 text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS morse_key_type_natural ON adif.morse_key_type (adif_version, abbreviation);

-- Primary_Administrative_Subdivision
CREATE TABLE IF NOT EXISTS adif.primary_administrative_subdivision (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    primary_administrative_subdivision       text,
    dxcc_entity_code                         integer,
    contained_within                         text,
    oblast_no                                text,
    cq_zone                                  text,
    itu_zone                                 text,
    prefix                                   text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
-- Primary_Administrative_Subdivision: no column set is unique in every version; reference it by record_key.

-- Propagation_Mode
CREATE TABLE IF NOT EXISTS adif.propagation_mode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    enumeration                              text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS propagation_mode_natural ON adif.propagation_mode (adif_version, enumeration);

-- QSL_Medium
CREATE TABLE IF NOT EXISTS adif.qsl_medium (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    medium                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qsl_medium_natural ON adif.qsl_medium (adif_version, medium);

-- QSL_Rcvd
CREATE TABLE IF NOT EXISTS adif.qsl_rcvd (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    meaning                                  text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qsl_rcvd_natural ON adif.qsl_rcvd (adif_version, status);

-- QSL_Sent
CREATE TABLE IF NOT EXISTS adif.qsl_sent (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    meaning                                  text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qsl_sent_natural ON adif.qsl_sent (adif_version, status);

-- QSL_Via
CREATE TABLE IF NOT EXISTS adif.qsl_via (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    via                                      text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qsl_via_natural ON adif.qsl_via (adif_version, via);

-- QSO_Complete
CREATE TABLE IF NOT EXISTS adif.qso_complete (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    abbreviation                             text,
    meaning                                  text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qso_complete_natural ON adif.qso_complete (adif_version, abbreviation);

-- QSO_Download_Status
CREATE TABLE IF NOT EXISTS adif.qso_download_status (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qso_download_status_natural ON adif.qso_download_status (adif_version, status);

-- QSO_Upload_Status
CREATE TABLE IF NOT EXISTS adif.qso_upload_status (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    status                                   text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS qso_upload_status_natural ON adif.qso_upload_status (adif_version, status);

-- Region
CREATE TABLE IF NOT EXISTS adif.region (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    region_entity_code                       text,
    dxcc_entity_code                         integer,
    region                                   text,
    prefix                                   text,
    applicability                            text,
    start_date                               timestamptz,
    end_date                                 timestamptz,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
-- Region: no column set is unique in every version; reference it by record_key.

-- Secondary_Administrative_Subdivision
CREATE TABLE IF NOT EXISTS adif.secondary_administrative_subdivision (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    secondary_administrative_subdivision     text,
    dxcc_entity_code                         integer,
    alaska_judicial_district                 text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS secondary_administrative_subdivision_natural ON adif.secondary_administrative_subdivision (adif_version, code);

-- Secondary_Administrative_Subdivision_Alt
CREATE TABLE IF NOT EXISTS adif.secondary_administrative_subdivision_alt (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    code                                     text,
    dxcc_entity_code                         integer,
    region                                   text,
    district                                 text,
    deleted                                  boolean,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS secondary_administrative_subdivision_alt_natural ON adif.secondary_administrative_subdivision_alt (adif_version, code);

-- Submode
CREATE TABLE IF NOT EXISTS adif.submode (
    adif_version text NOT NULL REFERENCES adif.release (adif_version),
    record_key   text NOT NULL,
    submode                                  text,
    mode                                     text,
    description                              text,
    import_only                              boolean,
    comments                                 text,
    record       jsonb NOT NULL,
    PRIMARY KEY (adif_version, record_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS submode_natural ON adif.submode (adif_version, submode);

-- Cross-references ADIF itself defines. A load that violates one fails whole.
ALTER TABLE adif.primary_administrative_subdivision DROP CONSTRAINT IF EXISTS primary_administrative_subdivision_dxcc_entity_code_fk;
ALTER TABLE adif.primary_administrative_subdivision ADD CONSTRAINT primary_administrative_subdivision_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.region DROP CONSTRAINT IF EXISTS region_dxcc_entity_code_fk;
ALTER TABLE adif.region ADD CONSTRAINT region_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.secondary_administrative_subdivision DROP CONSTRAINT IF EXISTS secondary_administrative_subdivision_dxcc_entity_code_fk;
ALTER TABLE adif.secondary_administrative_subdivision ADD CONSTRAINT secondary_administrative_subdivision_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.secondary_administrative_subdivision_alt DROP CONSTRAINT IF EXISTS secondary_administrative_subdivision_alt_dxcc_entity_code_fk;
ALTER TABLE adif.secondary_administrative_subdivision_alt ADD CONSTRAINT secondary_administrative_subdivision_alt_dxcc_entity_code_fk FOREIGN KEY (adif_version, dxcc_entity_code) REFERENCES adif.dxcc_entity_code (adif_version, entity_code);
ALTER TABLE adif.submode DROP CONSTRAINT IF EXISTS submode_mode_fk;
ALTER TABLE adif.submode ADD CONSTRAINT submode_mode_fk FOREIGN KEY (adif_version, mode) REFERENCES adif.mode (adif_version, mode);

-- The read-only role sees everything in this schema, now and later.
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ionis_ro') THEN
  GRANT USAGE ON SCHEMA adif TO ionis_ro;
  GRANT SELECT ON ALL TABLES IN SCHEMA adif TO ionis_ro;
  ALTER DEFAULT PRIVILEGES IN SCHEMA adif GRANT SELECT ON TABLES TO ionis_ro;
END IF; END $$;
