-- =============================================================================
-- File.........: 38-wspr_bronze_uniform.sql
-- Description..: wspr.bronze restricted to the minutes that are complete for all time
-- Engine.......: View (no storage)
-- Population...: n/a -- derived from wspr.bronze at query time
--
-- THIS VIEW EXISTED IN PRODUCTION FOR SEVENTEEN DAYS WITH NO DDL AND NO DOCS.
-- It was created by hand on 2026-09-05 during the backfill recovery and only
-- surfaced in the 2026-09-22 data audit, which had to reverse-engineer it from
-- SHOW CREATE. That is the failure this file closes: an object that silently
-- changes what a query means must be in the schema, not in someone's history.
--
-- WHAT IT IS FOR
--
-- Since 2023-10-16 wsprnet.org's monthly CSV export omits most spots in the first
-- ~10 minutes of every hour. Retention measured per 2-minute WSPR slot:
--
--     :00  0.9%   :02  0.8%   :04  1.4%   :06 13.3%   :08 69.1%   :10+ 100.0%
--
-- That ramp is an upload-latency cutoff: receivers upload a minute or two after
-- each transmission window, and the export reads its window before the late
-- arrivals land. By :10 everything has arrived, so :10-:58 is byte-perfect for
-- the entire history of the table.
--
-- It went unseen for about three years because hourly totals look completely
-- normal. The deficit only appears when you group by minute-of-hour -- which is
-- exactly why a view is the right remedy: the defect is invisible to the shape of
-- query that would otherwise catch it.
--
-- WHEN TO USE IT
--
-- Any hour-of-day, diurnal, or seasonal analysis spanning 2023-10 .. 2025-05.
-- Over that window wspr.bronze under-counts the first ten minutes of every hour,
-- and a GROUP BY hour reads it as a real propagation dip. It is not one.
--
-- cmd/wspr-backfill recovers the missing spots from wspr.live. IT IS FINISHED, AND
-- IT WAS NOT ENOUGH.
--
-- wspr.live did not escape the defect for that era either. Sampling the 15th of each
-- affected month, its own minute 0-9 retention matches ours to the percentage point:
-- 27.7/27.7 (2023-11), 21.1/21.1 (2024-02), 22.3/22.3 (2024-06), 15.5/15.5 (2024-08),
-- 16.7/16.7 (2024-12), 17.2/17.2 (2025-03), 22.2/22.2 (2025-04). Confirmed at ID level
-- rather than by count -- backfill dry runs on four separate months each returned
-- new=0, already-held=everything.
--
-- So roughly 392 MILLION spots across 2023-10-16 .. 2025-05-31 no longer exist anywhere
-- we can reach (206.09M held in minute 0-9 against a 597.68M reference from 10-19).
-- This view is therefore the ONLY correct source for time-of-day work over that span,
-- permanently.
--
-- WHEN NOT TO USE IT
--
-- Totals, coverage, and anything where completeness of the full hour is not the
-- question. The view discards ~17% of rows by construction, including rows that
-- are perfectly good for 2026 and for everything before 2023-10.
--
-- RETIREMENT: none. This view is permanent.
--
-- An earlier revision of this file said it could retire "when the backfill has covered
-- 2023-10 .. 2025-05". That condition can never be met -- the data is gone upstream, not
-- merely un-fetched. Do not drop this view expecting the gap to have closed; it will not.
-- Verify for yourself with the query in docs/DATA-DICTIONARY.md section 5 before
-- concluding otherwise.
-- =============================================================================

CREATE VIEW IF NOT EXISTS wspr.bronze_uniform AS
SELECT *
FROM wspr.bronze
WHERE toMinute(timestamp) >= 10;
